name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Debug dist contents
        run: ls -R dist

      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Package dist directory
        run: cd dist && zip -r ../tpanel-link_${{ env.VERSION }}.zip .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: tpanel-link_${{ env.VERSION }}.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true